### ISSUE TITLE
Can you please make https://colab.research.google.com/github/deezer/spleeter/blob/master/spleeter.ipynb#scrollTo=f8Brdfh6mzEz work?

### ISSUE THREAD

**Issue by DomDXD** [deezer/spleeter#921]
Hi,

The first 5 part of the scripts works fine but this line is missing stuff
!spleeter separate -h

-h is not even on option.

Can you please update it to make it work so I know how to use it properly?

Please and thank you,
Dominic.

**Comment by maciejgoscinski-latrace** [comment]
This stems from an earlier `pip install spleeter` step.
The installation step should be fixed, but also should *not8 silently proceed forward on errors.


```
Collecting spleeter
  Using cached spleeter-2.1.0-py3-none-any.whl.metadata (10 kB)
Collecting ffmpeg-python==0.2.0 (from spleeter)
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl.metadata (1.7 kB)
Collecting httpx<0.17.0,>=0.16.1 (from httpx[http2]<0.17.0,>=0.16.1->spleeter)
  Using cached httpx-0.16.1-py3-none-any.whl.metadata (38 kB)
Collecting librosa==0.8.0 (from spleeter)
  Using cached librosa-0.8.0.tar.gz (183 kB)
  Preparing metadata (setup.py) ... done
Collecting norbert==0.2.1 (from spleeter)
  Using cached norbert-0.2.1-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting numpy<1.19.0,>=1.16.0 (from spleeter)
  Using cached numpy-1.18.5.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by hybridherbst** [comment]
This issue persists – I think the title of the issue is a bit misleading. The Colab page currently doesn't work, due to the install error in spleeter / numpy.
